// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI-powered password advisor flow.
 *
 * - getPasswordAdvice - A function that provides feedback on password strength and suggests improvements.
 * - PasswordAdviceInput - The input type for the getPasswordAdvice function.
 * - PasswordAdviceOutput - The return type for the getPasswordAdvice function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PasswordAdviceInputSchema = z.object({
  password: z.string().describe('The password to evaluate.'),
  loginHistory: z.string().optional().describe('The login history of the user, can be used to suggest personalized improvements'),
});
export type PasswordAdviceInput = z.infer<typeof PasswordAdviceInputSchema>;

const PasswordAdviceOutputSchema = z.object({
  strength: z.string().describe('A qualitative assessment of the password strength (e.g., Weak, Moderate, Strong).'),
  suggestions: z.array(z.string()).describe('Specific suggestions for improving the password, based on common vulnerability patterns.'),
});
export type PasswordAdviceOutput = z.infer<typeof PasswordAdviceOutputSchema>;

export async function getPasswordAdvice(input: PasswordAdviceInput): Promise<PasswordAdviceOutput> {
  return passwordAdvisorFlow(input);
}

const passwordAdvisorPrompt = ai.definePrompt({
  name: 'passwordAdvisorPrompt',
  input: {schema: PasswordAdviceInputSchema},
  output: {schema: PasswordAdviceOutputSchema},
  prompt: `You are an AI-powered password advisor. Your role is to provide feedback on the strength of a given password and suggest improvements based on common vulnerability patterns.

Evaluate the following password:
{{{password}}}

Also consider the login history of the user, if provided:
{{{loginHistory}}}

Provide a strength assessment and specific suggestions to improve the password. Consider factors such as length, character diversity, common patterns (e.g., dictionary words, keyboard patterns), and known vulnerabilities.

Ensure that your suggestions are practical and actionable for the user.

Respond in a structured format with 'strength' and 'suggestions' fields.
`,
});

const passwordAdvisorFlow = ai.defineFlow(
  {
    name: 'passwordAdvisorFlow',
    inputSchema: PasswordAdviceInputSchema,
    outputSchema: PasswordAdviceOutputSchema,
  },
  async input => {
    const {output} = await passwordAdvisorPrompt(input);
    return output!;
  }
);
